#!/usr/bin/env bash
# Gracefully reloads Gunicorn.

set -e

if pgrep gunicorn > /dev/null; then
    echo "Reloading Gunicorn gracefully..."
    kill -HUP -v gunicorn
    echo "Gunicorn workers renewed."
else
    echo "Gunicorn is not running."
fi
