#!/usr/bin/env bash
# Gracefully reloads Gunicorn.

#Find the PID of the Gunicorn process
PID=$(ps ax | grep '[g]unicorn' | awk '{print $1}')

if [ -z "$PID" ]; then
    echo "Gunicorn is not running"
    exit 1
fi

# Send the HUP signal to the Gunicorn process
kill -HUP "$PID"
